### PR TITLE
fixed issue #90

### PR DESCRIPTION
**Pull request by PresidentNick**

### CODE REVIEW

**Comment by PresidentNick** [comment]
Did anyone ever notice this?

**Comment by dennereed** [comment]
What do you mean?


On July 24, 2015 at 3:42:26 PM, Nick (notifications@github.com) wrote:

Did anyone ever notice this?

**Comment by PresidentNick** [comment]
The pull request is still open, I was wondering if you forgot to accept it and implement.

**Comment by dennereed** [comment]
probably :-( I’ll check on it Monday. Thanks for pointing it out.

On July 24, 2015 at 4:26:43 PM, Nick (notifications@github.com) wrote:

The pull request is still open, I was wondering if you forgot to accept it and implement.

**Pull request closed without merging**
